# Generated by Django 3.1.4 on 2020-12-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_img', models.ImageField(upload_to='images/')),
                ('captcha_type', models.CharField(choices=[('W', 'WaterRipple Captcha'), ('S', 'Sina Captcha'), ('M', 'Mathematical Captcha')], default=('W', 'WaterRipple Captcha'), max_length=20)),
            ],
        ),
    ]
