# Generated by Django 3.1.4 on 2020-12-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackCaptcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchaimage',
            name='captcha_type',
            field=models.CharField(choices=[('WaterRipple', 'WaterRipple Captcha'), ('SIna', 'Sina Captcha'), ('Mathematical', 'Mathematical Captcha')], default=('WaterRipple', 'WaterRipple Captcha'), max_length=20),
        ),
    ]
