# Generated by Django 3.1.4 on 2020-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackCaptcha', '0002_auto_20201205_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrackCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(default=None, max_length=20)),
                ('captcha_type', models.CharField(choices=[('WaterRipple', 'WaterRipple Captcha'), ('Sina', 'Sina Captcha'), ('Mathematical', 'Mathematical Captcha')], default=('WaterRipple', 'WaterRipple Captcha'), max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='captchaimage',
            name='captcha_type',
            field=models.CharField(choices=[('WaterRipple', 'WaterRipple Captcha'), ('Sina', 'Sina Captcha'), ('Mathematical', 'Mathematical Captcha')], default=('WaterRipple', 'WaterRipple Captcha'), max_length=20),
        ),
    ]
